# General
exclude: [".gitignore", "README.md", "LICENSE"]

# Site settings
title: Pablo O Vieira
email: mail@povieira.com
description: > # this means to ignore newlines until "baseurl:"
  Pablo O Vieira personal website. Keywords: project management, agile,
  software, coding, programming, python, database, gamification
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://povieira.com" # the base hostname & protocol for your site

ga_tracking_code: UA-34825674-1

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
