# General
exclude:
  - ".gitignore"
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor

timezone: America/Sao_Paulo

# Site settings
title: Pablo O Vieira
email: mail@povieira.com

meta:
  description: "Pablo O Vieira personal website."
  keywords: project management, agile, software, coding, programming, python, database, gamification

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://povieira.com" # the base hostname & protocol for your site

branch: master

ga_tracking_code: UA-34825674-1

default_image: https://s.gravatar.com/avatar/80fc0ea8a3a2161074feb3725901d093?s=200

# Posts
permalink: /posts/:year/:month/:day/:title/

disqus_shortname: povieira

author: Pablo

# Profile
profile:
  name: Pablo O Vieira
  avatar: https://s.gravatar.com/avatar/80fc0ea8a3a2161074feb3725901d093?s=200

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
