# General
exclude:
  - ".gitignore"
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor

timezone: America/Sao_Paulo

# Site settings
title: Pablo Vieira
email: contact@povieira.com

app_name: PV

meta:
  description: "Pablo Vieira's personal website."
  keywords: software engineer, coding, programming, project management, agile, scrum, team, python, django, database, nosql, gamification, cto, lending, fintech
  theme_color: "#fff"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pv8.github.io" # the base hostname & protocol for your site

branch: main

ga_tracking_code: UA-34825674-1

hj_id: 527097

default_image: https://github.com/pv8.png

# Posts
permalink: /posts/:year/:month/:day/:title/

disqus_shortname: pv8

author: Pablo

# Profile
profile:
  name: Pablo Vieira
  avatar: https://github.com/pv8.png

pgp:
  fingerprint: 38EB FF7D 03DA E2D5 4D39 5007 3155 7CED BBAD 4FA3
  url: https://keybase.io/pv8/key.asc

# Build settings
markdown: kramdown

github: [metadata]

plugins:
  - jekyll-sitemap

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]
