# General
exclude:
  - ".gitignore"
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor

timezone: America/Sao_Paulo

# Site settings
title: Pablo Vieira
email: contact@pv8.io

app_name: PV

meta:
  description: "Pablo Vieira's personal website."
  keywords: project management, agile, scrum, coding, programming, python, database, nosql, gamification, cto, jeenga, marketing, crm
  theme_color: "#fff"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.pv8.io" # the base hostname & protocol for your site

branch: master

ga_tracking_code: UA-34825674-1

hj_id: 527097

default_image: https://s.gravatar.com/avatar/80fc0ea8a3a2161074feb3725901d093?s=200

# Posts
permalink: /posts/:year/:month/:day/:title/

disqus_shortname: pv8

author: Pablo

# Profile
profile:
  name: Pablo Vieira
  avatar: https://s.gravatar.com/avatar/80fc0ea8a3a2161074feb3725901d093?s=200

pgp:
  fingerprint: 38EB FF7D 03DA E2D5 4D39 5007 3155 7CED BBAD 4FA3
  url: https://keybase.io/pv8/key.asc

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]
